apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: redis 
  labels:
    app: redis-cluster
spec:
  ports:
    - name: client
      port: 6379
      protocol: TCP
      targetPort: 6379
    - name: cluster
      port: 16379
      protocol: TCP
      targetPort: 16379
  selector:
    app: redis-cluster
  type: ClusterIP
